Initial Global Perform Support
qaisjp/go-discord-irc pull request #71
Opened 2021-02-10 17:08 UTC by llmII

Allows for the bot to send raw messages to the IRC server for each connection spawned. Useful for networks that forcefully join newly connected users to a channel they have no intention of remaining in.

2021-02-10 17:32 UTC, qaisjp commented on bridge/irc_listener.go
> +	//execute peform
```suggestion
	// Execute global perform commands
```

2021-02-10 17:32 UTC, qaisjp requested changes
Thanks, this looks good.

- Probably want to use `SendRaw` instead of `SendRawf`
- `README.md` has a list of settings and needs to be updated (for the other PRs too)
- `config.yml` is missing a trailing newline

2021-02-10 17:33 UTC, qaisjp commented on bridge/irc_connection.go
> +		i.innerCon.SendRawf(com)
```suggestion
		i.innerCon.SendRaw(com)
```

2021-02-10 17:33 UTC, qaisjp commented on config.yml
> +#   - PRIVMSG Nick :msg
```suggestion
#   - PRIVMSG Nick :msg

```

2021-02-10 17:33 UTC, qaisjp commented on bridge/irc_listener.go
> +		i.SendRawf(com)
```suggestion
		i.SendRaw(com)
```

2021-02-10 18:10 UTC, llmII commented
> * `README.md` has a list of settings and needs to be updated (for the other PRs too)

I definitely need to do that. I'll tack on a commit soon for `README.md` where appropriate.

2021-02-16 02:10 UTC, qaisjp commented on bridge/irc_connection.go
> +	for _, com := range i.manager.bridge.Config.IRCGlobalPerform {
```suggestion
	for _, com := range i.manager.bridge.Config.IRCPrejoinCommands {
```

2021-02-16 02:10 UTC, qaisjp commented on bridge/irc_listener.go
> +	for _, com := range i.bridge.Config.IRCGlobalPerform {
```suggestion
	for _, com := range i.bridge.Config.IRCPrejoinCommands {
```

2021-02-16 02:13 UTC, qaisjp approved these changes
Thank you! This works really well. I changed the setting name.

2021-02-16 02:13 UTC, merged